AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Lyft Button API - The API for lyftbutton.com'

Parameters:
  Stage:
    Type: String
    Description: Stage of this stack. Can be Dev or Prod.
    AllowedValues:
      - Dev
      - Prod
    Default: 'Dev'

Mappings:
  SecretsMap:
    Dev:
      TokenSecret: '{{resolve:ssm:/LyftButton/Dev/TokenSecret:1}}'
      LyftClientId: '{{resolve:ssm:/LyftButton/Dev/LyftClientId:1}}'
      LyftClientSecret: '{{resolve:ssm:/LyftButton/Dev/LyftClientSecret:1}}'
      GoogleClientId: '{{resolve:ssm:/LyftButton/Dev/GoogleClientId:1}}'
      GoogleClientSecret: '{{resolve:ssm:/LyftButton/Dev/GoogleClientSecret:1}}'
    Prod:
      TokenSecret: '{{resolve:ssm:/LyftButton/Prod/TokenSecret:1}}'
      LyftClientId: '{{resolve:ssm:/LyftButton/Prod/LyftClientId:1}}'
      LyftClientSecret: '{{resolve:ssm:/LyftButton/Prod/LyftClientSecret:1}}'
      GoogleClientId: '{{resolve:ssm:/LyftButton/Prod/GoogleClientId:1}}'
      GoogleClientSecret: '{{resolve:ssm:/LyftButton/Prod/GoogleClientSecret:1}}'


Globals:
  Function:
    Timeout: 300
    Tags:
      Site: lyftbutton.com

Resources:
  LyftButtonApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: JWTAuthorizer
        Authorizers:
          JWTAuthorizer:
            FunctionArn: !GetAtt JWTAuthorizeFunction.Arn

  LyftButtonTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: LyftButton
      AttributeDefinitions:
        - AttributeName: lyft_id
          AttributeType: S
        - AttributeName: serial_number
          AttributeType: S
      KeySchema:
        - AttributeName: lyft_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: serial_number
          KeySchema:
            - AttributeName: serial_number
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Site
          Value: lyftbutton.com

  JWTAuthorizeFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.jwt_authorizer
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']

  GetLyftAccountFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.get_lyft_account
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']
          LYFT_CLIENT_ID: !FindInMap [SecretsMap, !Ref Stage, 'LyftClientId']
          LYFT_CLIENT_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'LyftClientSecret']
      Events:
        GetLyftUrl:
          Type: Api
          Properties:
            Auth:
              Authorizer: NONE
            RestApiId: !Ref LyftButtonApi
            Path: /lyft-account/url
            Method: get
        GetLyftAccount:
          Type: Api
          Properties:
            RestApiId: !Ref LyftButtonApi
            Path: /lyft-account
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LyftButtonTable

  CreateLyftAccountFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.create_lyft_account
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']
          LYFT_CLIENT_ID: !FindInMap [SecretsMap, !Ref Stage, 'LyftClientId']
          LYFT_CLIENT_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'LyftClientSecret']
      Events:
        CreateLyftAccount:
          Type: Api
          Properties:
            RestApiId: !Ref LyftButtonApi
            Auth:
              Authorizer: NONE
            Path: /lyft-account
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LyftButtonTable

  GetDashButtonFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.get_dash_button
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']
      Events:
        GetDashButton:
          Type: Api
          Properties:
            RestApiId: !Ref LyftButtonApi
            Path: /dash-button
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref LyftButtonTable

  EditDashButtonFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.edit_dash_button
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']
      Events:
        EditDashButton:
          Type: Api
          Properties:
            RestApiId: !Ref LyftButtonApi
            Path: /dash-button
            Method: patch
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LyftButtonTable

  GetGoogleAccountFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.get_google_account
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']
          GOOGLE_CLIENT_ID: !FindInMap [SecretsMap, !Ref Stage, 'GoogleClientId']
          GOOGLE_CLIENT_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'GoogleClientSecret']
      Events:
        GetGoogleAccount:
          Type: Api
          Properties:
            RestApiId: !Ref LyftButtonApi
            Path: /google-account
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LyftButtonTable

  SetGoogleAccountFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.set_google_account
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']
          GOOGLE_CLIENT_ID: !FindInMap [SecretsMap, !Ref Stage, 'GoogleClientId']
          GOOGLE_CLIENT_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'GoogleClientSecret']
      Events:
        SetGoogleAccount:
          Type: Api
          Properties:
            RestApiId: !Ref LyftButtonApi
            Path: /google-account
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LyftButtonTable

  DeleteGoogleAccountFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.delete_google_account
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']
      Events:
        DeleteGoogleAccount:
          Type: Api
          Properties:
            RestApiId: !Ref LyftButtonApi
            Path: /google-account
            Method: delete
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LyftButtonTable
