AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Lyft Button API - The API for lyftbutton.com'

Parameters:
  Stage:
    Type: String
    Description: Stage of this stack. Can be Dev or Prod.
    AllowedValues:
      - Dev
      - Prod
    Default: 'Dev'
  CorsDomain:
    Type: String
    Description: CORS authorized domain for this API
    Default: '*'
  DomainName:
    Type: String
    Description: Domain name for the API, e.g. api.lyftbutton.com
    Default: ''
  SSLCertificateArn:
    Type: String
    Description: Arn for an SSL certificate that covers the domain
    Default: ''
  HostedZoneId:
    Type: String
    Description: HostedZone to create record for the domain
    Default: ''

Mappings:
  SecretsMap:
    Dev:
      TokenSecret: '{{resolve:ssm:/LyftButton/Dev/TokenSecret:1}}'
      LyftClientId: '{{resolve:ssm:/LyftButton/Dev/LyftClientId:1}}'
      LyftClientSecret: '{{resolve:ssm:/LyftButton/Dev/LyftClientSecret:1}}'
      GoogleClientId: '{{resolve:ssm:/LyftButton/Dev/GoogleClientId:1}}'
      GoogleClientSecret: '{{resolve:ssm:/LyftButton/Dev/GoogleClientSecret:1}}'
    Prod:
      TokenSecret: '{{resolve:ssm:/LyftButton/Prod/TokenSecret:1}}'
      LyftClientId: '{{resolve:ssm:/LyftButton/Prod/LyftClientId:1}}'
      LyftClientSecret: '{{resolve:ssm:/LyftButton/Prod/LyftClientSecret:1}}'
      GoogleClientId: '{{resolve:ssm:/LyftButton/Prod/GoogleClientId:1}}'
      GoogleClientSecret: '{{resolve:ssm:/LyftButton/Prod/GoogleClientSecret:1}}'

Conditions:
  ShouldMapDomain: !Not [ !Equals [ !Ref DomainName, "" ]]

Globals:
  Function:
    Timeout: 300
    Environment:
      Variables:
        DYNAMO_TABLE_NAME: !Ref LyftButtonTable
        CORS_DOMAIN: !Ref CorsDomain
    Tags:
      Site: lyftbutton.com

Resources:
  LyftButtonApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: !Sub "'${CorsDomain}'"
        AllowHeaders: "'Authorization'"
      Auth:
        Authorizers:
          JWTAuthorizer:
            FunctionArn: !GetAtt JWTAuthorizeFunction.Arn

  CorsAuthResponse:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: !Sub "'${CorsDomain}'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'Authorization'"
      ResponseType: DEFAULT_4XX
      RestApiId: !Ref LyftButtonApi

  APIDomainName:
    Type: 'AWS::ApiGateway::DomainName'
    Condition: ShouldMapDomain
    Properties:
      CertificateArn: !Ref SSLCertificateArn
      DomainName: !Ref DomainName

  APIRedirectRecord:
    Type: 'AWS::Route53::RecordSet'
    Condition: ShouldMapDomain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: api.lyftbutton.com
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt APIDomainName.DistributionHostedZoneId
        DNSName: !GetAtt APIDomainName.DistributionDomainName

  APIBasePathMapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    Condition: ShouldMapDomain
    DependsOn:
      - LyftButtonApiProdStage
    Properties:
      DomainName: !Ref DomainName
      RestApiId: !Ref LyftButtonApi
      Stage: !Ref LyftButtonApi.Stage

  LyftButtonTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub "LyftButton-${Stage}"
      AttributeDefinitions:
        - AttributeName: lyft_id
          AttributeType: S
        - AttributeName: serial_number
          AttributeType: S
      KeySchema:
        - AttributeName: lyft_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: serial_number
          KeySchema:
            - AttributeName: serial_number
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Site
          Value: lyftbutton.com

  JWTAuthorizeFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.jwt_authorizer
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']

  GetLyftAccountFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.get_lyft_account
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']
          LYFT_CLIENT_ID: !FindInMap [SecretsMap, !Ref Stage, 'LyftClientId']
          LYFT_CLIENT_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'LyftClientSecret']
      Events:
        GetLyftUrl:
          Type: Api
          Properties:
            Auth:
              Authorizer: NONE
            RestApiId: !Ref LyftButtonApi
            Path: /lyft-account/url
            Method: get
        GetLyftAccount:
          Type: Api
          Properties:
            RestApiId: !Ref LyftButtonApi
            Path: /lyft-account
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LyftButtonTable

  CreateLyftAccountFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.create_lyft_account
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']
          LYFT_CLIENT_ID: !FindInMap [SecretsMap, !Ref Stage, 'LyftClientId']
          LYFT_CLIENT_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'LyftClientSecret']
      Events:
        CreateLyftAccount:
          Type: Api
          Properties:
            RestApiId: !Ref LyftButtonApi
            Auth:
              Authorizer: NONE
            Path: /lyft-account
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LyftButtonTable

  GetDashButtonFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.get_dash_button
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']
      Events:
        GetDashButton:
          Type: Api
          Properties:
            RestApiId: !Ref LyftButtonApi
            Path: /dash-button
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref LyftButtonTable

  EditDashButtonFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.edit_dash_button
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']
      Events:
        EditDashButton:
          Type: Api
          Properties:
            RestApiId: !Ref LyftButtonApi
            Path: /dash-button
            Method: patch
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LyftButtonTable

  GetGoogleAccountFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.get_google_account
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']
          GOOGLE_CLIENT_ID: !FindInMap [SecretsMap, !Ref Stage, 'GoogleClientId']
          GOOGLE_CLIENT_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'GoogleClientSecret']
      Events:
        GetGoogleAccount:
          Type: Api
          Properties:
            RestApiId: !Ref LyftButtonApi
            Path: /google-account
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LyftButtonTable

  SetGoogleAccountFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.set_google_account
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']
          GOOGLE_CLIENT_ID: !FindInMap [SecretsMap, !Ref Stage, 'GoogleClientId']
          GOOGLE_CLIENT_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'GoogleClientSecret']
      Events:
        SetGoogleAccount:
          Type: Api
          Properties:
            RestApiId: !Ref LyftButtonApi
            Path: /google-account
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LyftButtonTable

  DeleteGoogleAccountFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.delete_google_account
      Runtime: python3.6
      Environment:
        Variables:
          TOKEN_SECRET: !FindInMap [SecretsMap, !Ref Stage, 'TokenSecret']
      Events:
        DeleteGoogleAccount:
          Type: Api
          Properties:
            RestApiId: !Ref LyftButtonApi
            Path: /google-account
            Method: delete
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LyftButtonTable

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${LyftButtonApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
