AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Lyft Button API - The API for lyftbutton.com'

Parameters:
  TOKEN_SECRET:
    Type: String
    Description: Secret key to sign tokens
  LYFT_CLIENT_ID:
    Type: String
    Description: Lyft API Client ID
  LYFT_CLIENT_SECRET:
    Type: String
    Description: Lyft API Client Secret

Globals:
  Function:
    Timeout: 300
    Environment:
      Variables:
        TOKEN_SECRET: !Ref TOKEN_SECRET
        DYNAMO_ENDPOINT: !Ref DYNAMO_ENDPOINT
        LYFT_CLIENT_ID: !Ref LYFT_CLIENT_ID
        LYFT_CLIENT_SECRET: !Ref LYFT_CLIENT_SECRET

Resources:
  ButtonOfLyft:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      TableName: Token
      PrimaryKey:
        Name: lyft_id
        Type: String

  GetLyftAccountFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.get_lyft_account
      Runtime: python3.6
      Events:
        GetLyftAccount:
          Type: Api
          Properties:
            Path: /lyft-account
            Method: get

  CreateLyftAccountFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.create_lyft_account
      Runtime: python3.6
      Events:
        CreateLyftAccount:
          Type: Api
          Properties:
            Path: /lyft-account
            Method: post

  GetDashButtonFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.get_dash_button
      Runtime: python3.6
      Events:
        GetDashButton:
          Type: Api
          Properties:
            Path: /dash-button
            Method: get

  SetDashButtonHomeFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.set_dash_button_home
      Runtime: python3.6
      Events:
        SetDashButtonHome:
          Type: Api
          Properties:
            Path: /dash-button/home
            Method: post

  SetDashButtonDestinationFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: lyftbutton.set_dash_button_default_destination
      Runtime: python3.6
      Events:
        SetDashButtonDestination:
          Type: Api
          Properties:
            Path: /dash-button/destination
            Method: post
